### ISSUE TITLE
Execute  confluent-libserdes-3.3.0 c library example output error message.

### ISSUE THREAD

**Issue by passiondjc** [confluentinc/libserdes#11]
Hi, i use below command to run example
./serdes-kafka-avro-client -P -b 10.202.8.11:40301 -t testschema -p 1 -r http://localhost:8081 -s testvertica -S '{"type":"record","name""testvertica","namespace":"test","fields":[{"name":"f1","type":"string"},{"name":"f2","type":"string"}]}'

enter:str: {"f1":"value2", "f2":"value3"}

./serdes-kafka-avro-client -C -b 10.202.8.11:40301 -t testschema -p 1 -r http://localhost:8081
show error message:
Failed to read avro value: Cannot read string value: Cannot read string length: Cannot read 1 bytes from memory bufferCannot read string value: Cannot read string length: Cannot read 1 bytes from memory buffer

**Comment by pranayk01** [comment]
./serdes-kafka-avro-client -P -b localhost:9092 -t complex5 -r http://localhost:8081 -s cmp -S '{"type":"record","name":"movies","fields":[{"name":"title","type":"string"},{"name":"year","type":"string"},{"name":"genres","type":"string"}]}'
% Added schema cmp with id 3
% Use "schema: <json>" to specify a new schema
% Use "str: <string>" to produce an Avro-encoded string
% Ctrl-D to exit
str: {"title":"Tomorrowland","year":"2015","genres":"Mystery"}

./serdes-kafka-avro-client -C -b localhost:9092 -r http://localhost:8081 -X topic.auto.offset.reset=earliest -t complex5 -p 0 -X group.id=consumer-group3
% serdes_deserialize_avro failed: Failed to read avro value: Cannot read string value: Cannot read string length: Cannot read 1 bytes from memory buffer

Getting the same issue.
Any updates on this one?
