### ISSUE TITLE
Connection to Schema Registry with SSL authorization 

### ISSUE THREAD

**Issue by ktorunskilh** [confluentinc/libserdes#30]
If it is possible to connect to Schema Registry with enabled SSL authentication ? 

using kafkacat 
kafkacat -F admin.config -C -r https://schema-registry -s value=avro -t TOPIC

I'm receiving 
Avro/Schema-registry message deserialization: REST request failed (code -1): HTTP request failed: SSL connect error : terminating

admin.config
bootstrap.servers=broker:9093
security.protocol=ssl
ssl.ca.location=ca.crt
ssl.certificate.location=admin.crt
ssl.key.location=admin.key
ssl.key.password=xxx

Best regards,
Krzysiek

**Comment by edenhill** [comment]
The ssl.* configuration parameters are only for the Kafka client, not for the Schema registry client, it will only use the system's CA certificates.
