### ISSUE TITLE
Incompatibility with librdkafka

### ISSUE THREAD

**Issue by PaulaAlessio** [confluentinc/libserdes#43]
After this [issue](https://github.com/edenhill/librdkafka/issues/2681) was resolved in rdkafka, see change [here](https://github.com/edenhill/librdkafka/commit/7915f2a9adf30ca5938945c607b35c9c5a5a63e3), this conflicts with your defines in `tinythread` , leading sometimes to the error: 

`Failed to create thread: No such file or directory `

for an executable linking against both libraries simultaneously, since the defines mix up error and success. 

PS: we're using libserdes v7.0.0

**Comment by edenhill** [comment]
Fixed on master
