### ISSUE TITLE
libserdes self signed certificate path

### ISSUE THREAD

**Issue by pranmod** [confluentinc/libserdes#7]
Hi how do we specify selfsigned certificate path to libserdes to be used during schema server registration. I see from code it is using REST_POST but not taking certificate path as part of any of these APIs serdes_conf_new() and serdes_schema_add(). My schema registration is failing with following error "Failed to register schema name:<Topic> - REST request failed (code -1): HTTP request failed: Peer certificate cannot be authenticated with given CA certificates"

**Comment by edenhill** [comment]
It is using the system's default CA path location, but it does make sense to allow specifying an alternate path for self signed certs.

What we need to do is expose a new `ssl.certificate.location` configuration property that maps to `CURL_CAPATH`.

**Comment by pranmod** [comment]
Yes that would help. This is similar to how librdkafka is taking a SSL certificate path. When can we have this change?

**Comment by edenhill** [comment]
I can whip up a PR for you to try out next week.

**Comment by pranmod** [comment]
Hi Eden, do you have changes ready for this for me try it out.

**Comment by pranmod** [comment]
Hi Can you please let me know when this changes be available?
